[package]
name = "rsa-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.7.0"
rand = "0.8.5"
sha2 = "0.10.6"
signature = "1.6.4"

[profile.dev.package.num-bigint-dig]
opt-level = 3
